name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-precommit-${{ hashFiles('services/flow-engine/requirements.txt','services/messaging-gateway/requirements.txt','services/contacts/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pre-commit
        run: |
          python -m venv .venv
          . .venv/bin/activate; python -m pip install --upgrade pip; pip install pre-commit

      - name: Run pre-commit (strict)
        run: |
          . .venv/bin/activate; pre-commit run --all-files

  checks:
    needs: precommit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('services/flow-engine/requirements.txt','services/messaging-gateway/requirements.txt','services/contacts/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install repo venv and deps
        run: |
          python -m venv .venv
          . .venv/bin/activate; python -m pip install --upgrade pip; pip install -r services/flow-engine/requirements.txt; pip install -r services/messaging-gateway/requirements.txt; pip install -r services/contacts/requirements.txt; pip install pre-commit

      - name: Run make ci
        run: |
          . .venv/bin/activate; make ci
