name: E2E smoke test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('services/flow-engine/requirements.txt','services/messaging-gateway/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r services/flow-engine/requirements.txt
          pip install -r services/messaging-gateway/requirements.txt
      - name: Run unit tests (repo-wide)
        run: |
          pytest -q

  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start compose stack
        run: |
          docker compose up -d --build

      - name: Wait for Redis to be ready
        run: |
          for i in {1..30}; do
            docker compose exec -T redis redis-cli PING && break || sleep 1
          done

      - name: Run E2E smoke test
        run: |
          python3 scripts/e2e_test.py

      - name: Tear down
        if: always()
        run: |
          docker compose down -v
