name: E2E smoke test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start compose stack
        run: |
          docker compose up -d --build

      - name: Wait for Redis to be ready
        run: |
          for i in {1..30}; do
            docker compose exec -T redis redis-cli PING && break || sleep 1
          done

      - name: Run E2E smoke test
        run: |
          python3 scripts/e2e_test.py

      - name: Tear down
        if: always()
        run: |
          docker compose down -v
